#DEPLOYMENT CONFIGURATION FILE FOR GOOGLE CLOUD APP ENGINE
#app.yaml reference: https://cloud.google.com/appengine/docs/standard/nodejs/config/appref
runtime: nodejs

instance_class: F2
env: flex
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  # - url: /(.*\.(gif|png|jpg|ico|txt))$
  #   static_files: static/\1
  #   upload: static/.*\.(gif|png|jpg|ico|txt)$
  #   secure: always

  # - url: /.*
  #   script: auto
  #   secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'